### ISSUE TITLE
How to start a 16:9 ratio stream

### ISSUE THREAD

**Issue by Lazygarde** [pedroSG94/RootEncoder#1667] opened 2024-12-02 10:33 UTC
I tried to set a 16:9 ratio stream but the ratio still is 4:3. Even though i setTargetAspectRatio() for preview in CameraXSource but nothing happened. Can you help me? Thank you!

**Comment by pedroSG94** [comment] 2024-12-02 10:58
Hello,

Did you try to use a 16:9 aspect ratio resolution in prepareVideo method?

**Comment by Lazygarde** [comment] 2024-12-02 11:03
In CameraFragment (module App), i modified the width = 360 and height = 640. And i setTargetAspectRatio() in CameraXSource. Is it the right way?

**Comment by pedroSG94** [comment] 2024-12-02 11:23
> i modified the width = 360 and height = 640

why this?, this should be 640x360 and then modify rotation to 90 if you want rotate the stream.
Also, setTargetAspectRatio is not necessary

**Comment by Lazygarde** [comment] 2024-12-02 14:22
It's working well, thank you so much!
But why if i use the vertical rotation (w360, h640), the preview use 4:3 ratio

**Comment by pedroSG94** [comment] 2024-12-02 15:19
Hello,

I tested your case and it is working fine with Camera2Source. The preview is 16:9

I only replaced width to 360 and height to 640 in the CameraFragment class, If I use CameraXSource, it crash because the resolution is unsupported. I will check it but I can't reproduce exactly your case.

Can you tell me exactly the code modified to reproduce the case?

**Comment by Lazygarde** [comment] 2024-12-02 15:31
Yes, when i use 360w, 640h with CameraXSource, it crashes cause by unsupported resolution. 

Then i modified the ResolutionStrategy to ResolutionStrategy.FALLBACK_RULE_CLOSEST_LOWER, the ratio still is 4:3.

I also tried setTargetAspectRatio() for Preview.Builder() or setAspectRatioStrategy(AspectRatioStrategy.RATIO_16_9_FALLBACK_AUTO_STRATEGY) for ResolutionSelector.Builder(), nothing happened.

Because my project need cameraX, so i'm finding a way to fix that problem.

// Besides, in your previous comment, i've tried Camera2Source with 360w, 640h, but the preview is still 4:3, only when i use w > h (640w/360h or 1280w, 720h), the preview working well with both CameraX and Camera2, i don't know why, can you help me?

**Comment by pedroSG94** [comment] 2024-12-02 15:45
> Then i modified the ResolutionStrategy to ResolutionStrategy.FALLBACK_RULE_CLOSEST_LOWER, the ratio still is 4:3.

This make sense because with that line the library try to find the closest valid resolution to 360x640, in this case seems that the resolution choose is 640x480, I don't know the reason but I think that it is the case.

I will fix the app to support 360x640 or at least get a way to catch the error and allow the user control it.

**Comment by pedroSG94** [comment] 2024-12-02 15:47
> // Besides, in your previous comment, i've tried Camera2Source with 360w, 640h, but the preview is still 4:3, only when i use w > h (640w/360h or 1280w, 720h), the preview working well with both CameraX and Camera2, i don't know why, can you help me?

It is working fine for me. I don't understand. Did you only modify the width and height in CameraFragment class?

**Comment by Lazygarde** [comment] 2024-12-02 15:52
> It is working fine for me. I don't understand. Did you only modify the width and height in CameraFragment class? Can you share an image? Did you try stream and check if the stream resolution is working fine in the stream and only fail in preview?

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/f345a3af-46f7-4083-96b6-14deb4390325">
Yes, see my macbook, the preview is scaling

**Comment by Lazygarde** [comment] 2024-12-02 15:58
> I will fix the app to support 360x640 or at least get a way to catch the error and allow the user control it.

Not only 360x640, any resolution that w < h (480x640, 720x1280, 720x1080) with CameraX, it's also cause crash ...

**Comment by Lazygarde** [comment] 2024-12-02 16:04
> Did you try stream and check if the stream resolution is working fine in the stream and only fail in preview?

I've already check the stream resolution, the player (m3u8) still 4:3 ratio

**Comment by Lazygarde** [comment] 2024-12-02 16:14
Yes. Thank you for your support, i can use temporary solution is rotation 90.

**Comment by pedroSG94** [comment] 2024-12-02 21:43
Hello,

Fixed here:
https://github.com/pedroSG94/RootEncoder/commit/aaf2244f97e875af9d66eaec474d9c179675d1b9

Anyway, I recommend you allways use a resolution provided by getCameraResolutions method and set rotation to 90 if you want a portrait resolution as you are doing now.

**Comment by Lazygarde** [comment] 2024-12-03 04:48
I'm sorry, but i find a new issue

Using rotation 90 (w640, h360) will work fine with the preview, but the player is not good.
![image](https://github.com/user-attachments/assets/38047bd3-b3ec-4d9a-bbdc-996d2dbbe697)

Using your new solution will be ok
![image](https://github.com/user-attachments/assets/ce7356a9-3f67-4a41-b08f-916bd5f25773)

But maybe you should care this problem.

**Comment by pedroSG94** [comment] 2024-12-03 08:29
Hello,

I was testing it but I'm not able to reproduce your case. Did you test using other player?
For example VLC:
![imagen](https://github.com/user-attachments/assets/3194bab7-c617-4621-a0dd-6c32a02c5c99)

This is correct because, as you are doing, the rotation is selected to 0, so the resolution is 640x360 (landscape mode but device rotated to portrait)
![imagen](https://github.com/user-attachments/assets/39ebba49-2fad-4642-8f61-827a8d52076b)

This is the same stream when the device is rotated to landscape.
I have the same result using ffplay. Are you sure that your player is not distorting the image?

**Comment by pedroSG94** [comment] 2024-12-03 08:32
> Hello,
> 
> I was testing it but I'm not able to reproduce your case. Did you test using other player? For example VLC: ![imagen](https://private-user-images.githubusercontent.com/17556876/391872560-3194bab7-c617-4621-a0dd-6c32a02c5c99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTQ4NTAsIm5iZiI6MTczMzIxNDU1MCwicGF0aCI6Ii8xNzU1Njg3Ni8zOTE4NzI1NjAtMzE5NGJhYjctYzYxNy00NjIxLWEwZGQtNmMzMmEwMmM1Yzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMGFlODZkZDEyNGMwNmYzZjVlYTNkODc4MDQ1MDRlMmNlNTczNWU4NDNjMDI3MTNmN2QwY2ExOGQ4NTc3MTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.1Lw5JeaMjO3cm7tjTgpALAn8CsVwHa7CtGzMMErIFU8)
> 
> This is correct because, as you are doing, the rotation is selected to 0, so the resolution is 640x360 (landscape mode but device rotated to portrait) ![imagen](https://private-user-images.githubusercontent.com/17556876/391873741-39ebba49-2fad-4642-8f61-827a8d52076b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyMTQ4NTAsIm5iZiI6MTczMzIxNDU1MCwicGF0aCI6Ii8xNzU1Njg3Ni8zOTE4NzM3NDEtMzllYmJhNDktMmZhZC00NjQyLThmNjEtODI3YThkNTIwNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDA4MjkxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3MzY3NWYwNTFhMDdlY2Y2YjMxNWQ3ZGQ0MmRjNTMzOWY1YWIxZDczZDZhYjI3OWNiYzIyMTA2NmQ4OTJhNjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.S64rJBLLXIy3Zpa5NXqoHMuJDL8g4ChCrMPBuuQ5QR4)
> 
> This is the same stream when the device is rotated to landscape. I have the same result using ffplay. 
Using rotation to 90:
![imagen](https://github.com/user-attachments/assets/08f47b6e-b100-4fd3-98bb-3a74216ac848)

Are you sure that your player is not distorting the image?

**Comment by Lazygarde** [comment] 2024-12-03 08:46
Maybe the problem is the preset i config on CDN is portrait, because i need portrait stream. But i don't really understand why you use rotation 90 for a portrait stream

![image](https://github.com/user-attachments/assets/d0aa9b49-984f-4f07-9b59-0dc8024a32f0)

**Comment by pedroSG94** [comment] 2024-12-03 09:03
Hello,

That image is using 1280x720 and rotation 90 or 1280x720 and rotation 0?
If you use rotation 0 that result could be expected if your player force use 720x1280 because the original stream is 1280x720 so your player distort the image.

My reason to use rotation 90 for portrait is because the resolution for video source always is indicated in landscape when you open the camera or get resolutions for the source, the rotation parameter is used to indicate that you want the stream rotated 90 so if you set resolution 640x360 and you rotate the image 90 the result is 360x640 and if you have 360x640 and rotate 90 the image is 640x360.
My logic according with this to implement support to multiple resolutions is:
- Get supported resolutions using getCameraResolutions
- Set the resolution from that method in prepareVideo
- Use rotation 90 if you want portrait resolution or rotation 0 for landscape resolution

Of course, remove rotation and use the resolution as you are doing (switch values to use portrait) is also a valid way to work.

**Comment by Lazygarde** [comment] 2024-12-03 09:10
> That image is using 1280x720 and rotation 90 or 1280x720 and rotation 0?

This player is using the preset i config on CDN (720w, 1280h, 0rotation)

With my case (need a portrait stream), i should use portrait resolution and rotation 0, shouldn't me?

**Comment by pedroSG94** [comment] 2024-12-03 09:23
> > That image is using 1280x720 and rotation 90 or 1280x720 and rotation 0?
> 
> This player is using the preset i config on CDN (720w, 1280h, 0rotation)
> 
> With my case (need a portrait stream), i should use portrait resolution and rotation 0, shouldn't me?

Yes, that is fine, I only want confirm that 1280x720 with rotation 90 is working for you because it should be the same that 720x1280 with rotation 0.

**Comment by Lazygarde** [comment] 2024-12-03 09:35
Yes, it's working well

**Comment by pedroSG94** [comment] 2024-12-03 17:48
Ok, Closing as solved. Open other issue if you need it.

**Closed by pedroSG94** 2024-12-03 17:48 UTC
