### ISSUE TITLE
Play videos with 90 degree rotation when 'Surface filter' is used

### ISSUE THREAD

**Issue by mysangle** [pedroSG94/RootEncoder#1349] opened 2023-11-22 02:28 UTC
**Describe the bug**
If I use a video with a 90-degree orientation in the 'Surface Filter', the video is played with a 90-degree rotation.

**To Reproduce**
play video whose orientation is 90 degree in 'Surface filter'

**Expected behavior**
video should be played with correct rotation

**Screenshots**
<img width="475" alt="Screenshot" src="https://github.com/pedroSG94/RootEncoder/assets/941300/5541c87d-8e70-4a09-926a-264f5d0dcc4a">

Below is the video I played.

https://github.com/pedroSG94/RootEncoder/assets/941300/492743f1-5c47-49b3-bcda-32feb77a5799

**Smartphone (please complete the following information):**
 - Library version : 2.3.2
 - Device: Galaxy Z Fold3 and any other phones
 - OS: Android 13

**Additional context**
In demo app, when 'Surface filter' is used during streaming, MediaPlayer is attached with Surface of 'SurfaceFilterRender'.
However, MediaPlayer does not check video's orientation.

**Comment by pedroSG94** [comment] 2023-11-22 11:20
Hello,

This is not a bug at all because SurfaceFilter is not only oriented to be used with MediaPlayer. Since MediaPlayer ignore orientation metadata of the video when you reproduce it in a surface. I will create a feature to allow rotation to object filters (text, image, gif, and surface) that will fix the problem.
I will use this PR for the case:
https://github.com/pedroSG94/RootEncoder/pull/1350

**Comment by pedroSG94** [comment] 2023-11-27 22:44
Hello,

Finally I added rotation feature. Using your video in the app example with this configuration:
```java
surfaceFilterRender.setRotation(270); //rotate surface filter to use vertical
surfaceFilterRender.setScale(30f, 53.33f); //config scale to keep aspect ratio
```
This is the result:
![vtest](https://github.com/pedroSG94/RootEncoder/assets/17556876/6dfcc987-acee-48c9-8c0e-20745068eafa)

You can test it with the PR:
https://github.com/pedroSG94/RootEncoder/pull/1350

Let me know if it is working as you expected. I will test a bit and merge it

**Comment by pedroSG94** [comment] 2023-12-01 10:25
Closing as resolved

**Closed by pedroSG94** 2023-12-01 10:25 UTC
Labels: enhancement
