### ISSUE TITLE
ScreenSource why rotate display

### ISSUE THREAD

**Issue by LiPengfei0106** [pedroSG94/RootEncoder#1438] opened 2024-03-19 08:03 UTC
[https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/util/sources/video/ScreenSource.kt](url)

```kt
override fun start(surfaceTexture: SurfaceTexture) {
    this.surfaceTexture = surfaceTexture
    if (!isRunning()) {
      val dpi = context.resources.displayMetrics.densityDpi
      val flags = DisplayManager.VIRTUAL_DISPLAY_FLAG_AUTO_MIRROR
      //Adapt MediaProjection render to stream resolution
      val shouldRotate = width > height
      val displayWidth = if (shouldRotate) height else width
      val displayHeight = if (shouldRotate) width else height
      if (shouldRotate) {
        surfaceTexture.setDefaultBufferSize(height, width)
      }
      handlerThread.start()
      val mediaProjectionCallback = object : MediaProjection.Callback() {}
      mediaProjection.registerCallback(mediaProjectionCallback, Handler(handlerThread.looper))

      val callback = object : VirtualDisplay.Callback() {}
      virtualDisplay = mediaProjection.createVirtualDisplay("ScreenSource",
        displayWidth, displayHeight, dpi, flags,
        Surface(surfaceTexture), callback, Handler(handlerThread.looper)
      )
    }
  }
```

Displaywidth height is always greater than displaywidth. This will cause the landscape screen to be stretched.

**Comment by pedroSG94** [comment] 2024-03-19 09:47
Hello,

This should be fixed here (I had no time to test it well yet):
https://github.com/pedroSG94/RootEncoder/pull/1439

You can test it and let me know if the problem is solved. Also, you can suggest changes if you find a better way to implement this.

**Comment by pedroSG94** [comment] 2024-04-03 10:35
Closed as complete

**Closed by pedroSG94** 2024-04-03 10:35 UTC
