### ISSUE TITLE
If the stream is pushed to the servers for more than 4 hours, the servers will report an error

### ISSUE THREAD

**Issue by whr18756973961** [pedroSG94/RootEncoder#1179] opened 2022-10-14 12:42 UTC
When we use rtmp to push to the server, the server will report an error after 4-5 hours. The problem is that when reading the flvpacket sent by the client, the messageLength in the read flvpacket header is inconsistent with the actual flvpacket packet length, causing the server to fail to parse

**Comment by pedroSG94** [comment] 2022-10-27 07:16
Hello,

Sorry for late response. Do you have a way to reproduce the error? I need server name and version. If you have any configuration I will need it too.
Also, can you provide a log about the error?

**Comment by andrei72z** [comment] 2024-01-08 16:15
The error can be reproduced if you transmit packets with BufferInfo.presentationTimeUs>16777215000. The problem seems to be with the timestamp/extended timestamp in the RTMP header.

**Comment by pedroSG94** [comment] 2024-01-08 17:06
Hello,

Thank you for the info. Can you tell me server used for the test?

**Comment by pedroSG94** [comment] 2024-01-08 18:30
I was testing with mediamtx server version 1.4.2 and it is working fine. 
Also, I checked the header using wireshark and all is working as expected. You can check the extension timestamp here:
![imagen](https://github.com/pedroSG94/RootEncoder/assets/17556876/abbff23e-cb46-4b94-bdc3-7bd2cec13a6a)

**Comment by andrei72z** [comment] 2024-01-09 10:56
I tested with mediamtx 1.3.1 and Telegram server. Both servers break connection at the start of streaming if video encoding has been going on for more than 4 hours

**Comment by pedroSG94** [comment] 2024-01-09 13:59
Yes, mediamtx 1.3.1 fail with extended timestamp and it was fixed in version 1.4.1:
https://github.com/bluenviron/mediamtx/releases/tag/v1.4.1

I will try to check using others servers like telegram and notify here the result and server used for the test.

**Comment by pedroSG94** [comment] 2024-01-11 22:13
I tested multiple servers with extended timestamp as suggested and all is working. Severs used:
https://github.com/iizukanao/node-rtsp-rtmp-server
https://github.com/ossrs/srs
https://github.com/arut/nginx-rtmp-module
https://github.com/bluenviron/mediamtx
Youtube
Twitch

In all cases using the last server version but I couldn't reproduce the problem.
The problem only can be reproduced with mediamtx version 1.4.0 or lower but that server had a bug in extended timestamp so I can't count it.

I was no able to test using telegram.

I will mark this as help wanted for now. I need know how to connect to telegram stream to reproduce the problem and check the difference with ffmpeg extended timestamp to know the way to implemented it correctly or discard the bug

**Comment by andrei72z** [comment] 2024-01-12 12:06
To start rtmp streaming in Telegram you need to install "Telegram Desktop", create a group or channel and click "Stream with other apps". Use "Server URL"+"Stream key" as url for streaming. But perhaps there is some other problem here, not related to the timestamp, because I discovered that streaming only audio works even after 4 hours after starting encoding. Although the workaround (reset presentationTimeUs at the start of streaming) makes it possible to start video streaming at any time

**Comment by pedroSG94** [comment] 2024-01-14 23:21
Hello,

After multiple tests using telegram. I discover the error using that server.
That server seems to fail if you don't use incremental timestamp no matter the packet type (audio/video) when extended timestamp is used.
Others servers like Dacast require this but from start so you can solve it using this:
```java
rtmpCamera1.getStreamClient().forceAkamaiTs(true);
```
Remember call is before startStream.

After use that line the problem is totally solved using telegram. I haven't this problem using others servers so I think it is a bug in telegram server

**Closed** 2024-02-26 10:43 UTC
Labels: help wanted
