### ISSUE TITLE
Trying to record screen and stream the feed on Youtube Live, no errors but feed not showing up.

### ISSUE THREAD

**Issue by sanketsirohiya** [pedroSG94/RootEncoder#1545] opened 2024-08-16 04:06 UTC
Hi, I am trying to record my android screen and send the feed to YouTube Live. There are no errors that I see, but the feed is not visible on youtube. I have started a stream on YouTube Studio and used the stream URL and stream key in the code while calling the srsFlvMuxer.start(rtmpUrl) method. The permission for screen recording was also successfully given and recording notification is in place.

Have tried multiple things but am not able to get it to work. Would really appreciate some help here. Attaching the code files. Thanks in advance.

[ScreenRecording.zip](https://github.com/user-attachments/files/16632771/ScreenRecording.zip)

**Comment by pedroSG94** [comment] 2024-08-16 09:11
Hello,

First of all, That library version is really old. I recommend you use the last library version and replace srsFlvMuxer to RtmpClient.

Also, you have a code example to stream screen without implement encoder and others things yourself:
https://github.com/pedroSG94/RootEncoder/tree/master/app/src/main/java/com/pedro/streamer/screen

Anyway, I did a fast check in your code and I could see that you are not using setSPSandPPS method. You need do it when mediacodec return you on output format changed:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/BaseEncoder.java#L197
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/video/VideoEncoder.java#L305

**Comment by sanketsirohiya** [comment] 2024-08-29 12:18
Hi, thanks for your response. I tried to implement the code from the following link

**Comment by sanketsirohiya** [comment] 2024-08-29 12:25
Hi, thanks for your response. I tried to implement the code from the suggested link without the encoder etc. and updated the library version to the latest (  implementation 'com.github.pedroSG94.RootEncoder:library:2.4.9' ), updated my kotlin version to 2.0.0 that the library supports, but then ran into some errors from react-native-gesture-handler due to the change in kotlin version. 

Error: Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type 'com.swmansion.gesturehandler.core.GestureHandler<*>?'.

I tried updating react-native-gesture-handler to latest version but that did not work as well.

Can you please help with with an alternate version of your library that would work with Kotlin 1.8.0 and still let me use the approach without the encoder? 

Or would you suggest I continue with the encoder approach from before and implement the setSPSandPPS method?

**Comment by pedroSG94** [comment] 2024-08-30 08:18
Hello,

Did you try with kotlin 1.9.0?
Also, you can try to upgrade android gradle plugin to 8.5.0. If you upgrade it to 8.5.0 and use kotlin 1.8.0 all is wokring fine for me.

**Comment by pedroSG94** [comment] 2024-08-30 08:36
If the problem persist I can create you a version with kotlin 1.8.0 but this is an error in react native. 
This should be solved by them.

**Comment by pedroSG94** [comment] 2024-08-30 08:40
Also, I found that a user resolved your error here:
https://github.com/software-mansion/react-native-gesture-handler/issues/2427#issuecomment-2216609142

**Comment by sanketsirohiya** [comment] 2024-09-02 19:19
Hi, thanks again for your prompt response. 

I do agree that the error is from react-native-gesture-handler side, but I'm guessing they might take a while to fix this. 

I also did try the last link you've shared to fix the error, but there were other errors in different files that came up.

You suggested building a version with Kotlin 1.8.0, if thats easy enough to do, it would mean a lot. Or I could go through the encoding steps myself by adding the setSPSandPPS method in my previous implementation. 

What do you suggest?

**Comment by pedroSG94** [comment] 2024-09-02 23:07
In this case I did a release using Kotlin 1.8.22. 

This is an exception and I have no plan to continue the compilation in the future so try to migrate to use last Kotlin version as soon as possible.

```gradle
implementation 'com.github.pedroSG94.RootEncoder:library:2.5.0-1.8.22'
```

**Comment by sanketsirohiya** [comment] 2024-09-04 07:49
Hi, I am able to stream my screen to Youtube with the above version.

Really appreciate you taking the effort to compile it for me. I will try to upgrade to the latest whenever possible.

Can't thank you enough, cheers!

**Comment by sanketsirohiya** [comment] 2024-09-05 12:39
Hi, 

Regret to reopen this issue - the stream to Youtube worked fine, except for 1 issue: -

I have a live stream app, which is joined by other broadcasters apart from myself. My audio and my screen is perfectly streamed to Youtube but the incoming audio from the other broadcasters are not audible on the Youtube Live Stream. Is there a solution for this?

Please let me know if its simpler for you to track this in a separate issue, I can open it as a different one.

**Comment by pedroSG94** [comment] 2024-09-05 13:00
Hello,

I don't understand your question.

What do you mean with "app which is joined by other broadcasters apart from myself"?
A video call or meet?

Keep in mind 2 things:
- If you are using Microphone audio source the audio provided by the phone is not detected. Sometimes you have an exception if the audio from speakers is captured by the microphone.

- If you are using Internal audio source, the audio/video capture can be restricted by the app. For example, if you open Netflix, the audio and video can't be captured because the app block it.

**Comment by sanketsirohiya** [comment] 2024-09-05 13:27
Hi, thanks again for your quick response.

Yes it is like a video call which is joined by me + other broadcasters. Audio from my microphone is captured but the incoming audio from the other broadcasters which is being output from my phone is not captured.

Is there a solution for this?

**Comment by pedroSG94** [comment] 2024-09-05 17:44
Hello,

Currently the library only support audio from microphone or from the device. Get both audios is not possible for now. 
I have plan to implement this feature but it is not easy because I need mix both PCM audios and sync it.

**Comment by sanketsirohiya** [comment] 2024-09-05 19:21
I understand, although it breaks my heart to know this. 

Are you aware of any other source that I can use for this case? Alternatively, just to get a sense, do you have any rough idea about when we can expect the library to support both the device and mic audio?

**Comment by pedroSG94** [comment] 2024-09-05 20:23
I'm not sure about the time. I'm already working on it and I have a first version but with really bad results.

The audio is missed and sync but the result has a really bad quality but I don't know the exact reason so the release date  for this feature depend of my free time to do it and the luck debugging the case.

Also, for now. I only tested in mono and 44100 sample rate so maybe after solve it for this config. I need fix it for others configurations.

You can follow the development and collaborate if you want. This is the PR:
https://github.com/pedroSG94/RootEncoder/pull/1571

**Comment by noho501** [comment] 2024-09-08 13:47
Hi @pedroSG94 

Is this the same issue where, when I turn on the microphone, the sound from the PUBG game isn’t recorded, but when I turn off the microphone, the game sound is recorded? Please see the attached video: https://drive.google.com/file/d/12JBlI0wn-AgErcMbONOjc9CMFsU46HiC/view?usp=drivesdk

This is code we use:

  var muted = false

  fun toggleMute() {
      if (muted) {
        genericStream.changeAudioSource(MicrophoneSource())
        muted = false
      } else {
        mediaProjection?.let {
          if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            genericStream.changeAudioSource(InternalAudioSource(it))
            muted = true
          }
        }
      }
  }

**Comment by pedroSG94** [comment] 2024-09-08 13:56
Yes, this is the same case.

In your code you change microphone to internal audio. 
Internal audio is used to capture audio from apps and microphone capture only audio from the device microphone.

I'm working on a source that mix both audios, allowing capture both at the same time.

**Comment by noho501** [comment] 2024-09-08 14:00
Thank you for your reply. Do you know how to switch to the brand feature/audio-mix-source branch so we can test it with our source?

**Comment by pedroSG94** [comment] 2024-09-08 15:09
Hello,

I just finish the development (I'm currently doing tests in different sample rate, channels, etc to confirm that all is working fine).
That branch currently allow you audio AudioMixSource that include both. Microphone and InternalAudio sources. Also, allow control the volume of both sources.
If you want use the branch, clone the project with git and change to the branch using:
```
git checkout feature/audio-mix-source
```
Remember do a git pull if you already have the project cloned.
Also, you can download the project directly in that branch as zip, unzip and open it in Android studio:
https://github.com/pedroSG94/RootEncoder/archive/refs/heads/feature/audio-mix-source.zip

**Comment by noho501** [comment] 2024-09-08 15:37
Thank you so much. We will check it out and get back to you.

**Comment by sanketsirohiya** [comment] 2024-09-11 11:59
Hi, great to hear the progress on the mix audio source, eagerly waiting!

In the meantime, could you please help me with one other problem? The stream on Youtube is coming up in Landscape mode, is there a way to switch it to Portrait though code or any other setting that you are aware of?

Thanks!

**Comment by pedroSG94** [comment] 2024-09-11 12:57
> Hi, great to hear the progress on the mix audio source, eagerly waiting!
> 
> In the meantime, could you please help me with one other problem? The stream on Youtube is coming up in Landscape mode, is there a way to switch it to Portrait though code or any other setting that you are aware of?
> 
> Thanks!

Hello,

You only need set rotation in prepareVideo method to 90. In the app example using rotation example you can change it in the menu -> orientation -> vertical.

Remember that using the app this change have effect while you are not recording/streaming, because you need configure it in prepareVideo, and you can't call it while recording/streaming.

https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L160

**Comment by sanketsirohiya** [comment] 2024-09-12 12:18
Hi, setting the rotation works! However to capture the full screen I retrieved the device height and width (2209 and 1080 respectively) and on passing this to the prepareVideo function, I am getting the following error: -

Create VideoEncoder failed. java.lang.IllegalArgumentException: 

It works with the hardcoded height = 480, width = 640, as seen on the sample app but I there was either a lot of unnecessary whitespace around the recorded screen/ or sometimes I even noticed a part of the screen being captured as expected by the landscape nature of the 480 Height and 640 Width. Am I missing something?

I referred to the top few answers here to get the height and width - 
https://stackoverflow.com/questions/4743116/get-screen-width-and-height-in-android#:~:text=Display%20display%20%3D%20getWindowManager().,x%3B%20int%20height%20%3D%20size.

**Comment by pedroSG94** [comment] 2024-09-12 14:08
hello,

2209 is not a valid value you need set even values. Also, depend of your video source if you are using camera2 the value must be between the min and the max camera values. You have the rule here:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/util/sources/video/Camera2Source.kt#L65

**Comment by pedroSG94** [comment] 2024-09-12 14:09
My recommendation is use a value listed in getCameraResolutions method

**Comment by sanketsirohiya** [comment] 2024-09-12 16:23
Using even numbers worked! Thanks again for the quick support. 

Hate to trouble again and again, but is there also a way to save the recorded media on the device as an mp4 or something?

**Comment by sanketsirohiya** [comment] 2024-09-12 16:23
Youtube allows downloading the Stream after a few hours and that sometimes poses as a blocker.

**Comment by pedroSG94** [comment] 2024-09-12 16:47
Hello,

Try using startRecord and stopRecord methods. You can start or stop while streaming or without streaming.

Example here:

https://github.com/pedroSG94/RootEncoder/blob/master/app/src/main/java/com/pedro/streamer/rotation/CameraFragment.kt#L132

**Comment by sanketsirohiya** [comment] 2024-09-12 20:38
Thanks for sharing this. Tried it out and it works really well. :)

**Comment by pedroSG94** [comment] 2024-09-13 22:51
MixAudioSource merged to master. 
You can test it in the app example -> screen example -> menu -> mix audio

Closing as solved, you can reopen it if you find a bug or create other issue

**Comment by noho501** [comment] 2024-09-14 09:20
> Hello,
> 
> I just finish the development. I'm currently doing tests in different sample rate, channels, etc to confirm that all is working fine). That branch currently allow you use AudioMixSource that include both. Microphone and InternalAudio sources. Also, allow control the volume of both sources. If you want use the branch, clone the project with git and change to the branch using:
> 
> ```
> git checkout feature/audio-mix-source
> ```
> 
> Remember do a git pull if you already have the project cloned. Also, you can download the project directly in that branch as zip, unzip and open it in Android studio: https://github.com/pedroSG94/RootEncoder/archive/refs/heads/feature/audio-mix-source.zip

Hi @pedroSG94 

It’s not working in my case. When playing PUBG, if I turn on the in-game microphone and then enable the microphone in my app, no audio is recorded in the video or live stream. However, if I turn off my app’s microphone, the audio is recorded properly. Any suggestions?

**Comment by pedroSG94** [comment] 2024-09-14 15:06
Hello,

Did you try using master branch with screen example? Can you try open YouTube instead of PUBG and tell me the result?

**Comment by noho501** [comment] 2024-09-14 23:05
Hi @pedroSG94,

YouTube is working fine, but the problem occurs when the in-game or in-app microphone is enabled. I believe this is related to granting microphone permissions to the application, which results in our app being unable to record audio to the video file.

**Comment by pedroSG94** [comment] 2024-09-14 23:19
I see. 

PUBG app get the microphone producing no audio result. This has logic because the new class wait capture the microphone and device audio and then mix it. If no audio is received, never produce audio.

I'm not sure if we can reproduce this case with other audio app. Use PUBG sounds like a pain to debug.
Can you confirm me if this happens with an app to record audio?

**Comment by pedroSG94** [comment] 2024-09-14 23:27
I think that capturing the microphone at the same time that other apps may not be possible but I can try to recover the microphone audio after the app stops using it and meanwhile only sends device audio

**Comment by noho501** [comment] 2024-09-15 01:33
Hi @pedroSG94 

Do you think we should use an external microphone to avoid conflicts with the in-game or in-app microphone during recording?

https://stackoverflow.com/questions/74135716/is-there-any-way-to-determine-which-mic-of-android-phone-is-being-used-for-recor#:~:text=Most%20android%20smartphone%20has%20two,and%20One%20at%20the%20bottom.

**Comment by sanketsirohiya** [comment] 2024-09-16 11:10
Hi, Glad to hear that the Mix Audio Support is now complete. Can you confirm if there is a new version that you have released with this? I tried to sync my project but didn't see the MixAudioSource as part of the source. 

To remind, I am using this version currently

**Comment by pedroSG94** [comment] 2024-09-16 11:21
Hello,

No, it is not release yet because a bug was reported where the audio is not working if other app capture microphone. 
In this case this app lose the access to microphone and audio stop send. I want fix it first.

For now a solution is copy the source code of the new Audio source:
https://github.com/pedroSG94/RootEncoder/blob/master/library/src/main/java/com/pedro/library/util/sources/audio/MixAudioSource.kt

If you have a suggestion or fix, it is welcome.

**Comment by sanketsirohiya** [comment] 2024-09-16 14:33
Hi @pedroSG94 

I tried to copy the source code for MixAudioSouce.kt and VolumeEffect.kt but was not able to use some methods/members. Attached is the screenshot. 

Am I missing something? 
Thanks.

![Uploading Screenshot 2024-09-16 at 8.00.17 PM.png…]()

**Comment by sanketsirohiya** [comment] 2024-09-16 14:36
Hi @pedroSG94 ,

I tried to copy the source code for MixAudioSource.kt and VolumeEffect.kt as suggested, but am not able to use some methods/members (Screenshot Attached)

Am I missing something?

Thanks.

<img width="784" alt="Screenshot 2024-09-16 at 8 00 17 PM" src="https://github.com/user-attachments/assets/e1a24407-88c8-470d-8e89-f96218f9a805">

**Comment by pedroSG94** [comment] 2024-09-16 15:52
> Hi @pedroSG94 ,
> 
> I tried to copy the source code for MixAudioSource.kt and VolumeEffect.kt as suggested, but am not able to use some methods/members (Screenshot Attached)
> 
> Am I missing something?
> 
> Thanks.
> 
> <img alt="Screenshot 2024-09-16 at 8 00 17 PM" width="784" src="https://private-user-images.githubusercontent.com/29568414/367801406-e1a24407-88c8-470d-8e89-f96218f9a805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDIxMTcsIm5iZiI6MTcyNjUwMTgxNywicGF0aCI6Ii8yOTU2ODQxNC8zNjc4MDE0MDYtZTFhMjQ0MDctODhjOC00NzBkLThlODktZjk2MjE4ZjlhODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1NTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGVlMTFjMmUxYmVlODVkNzQ3NjgyN2VmZTM4ODcwYTFkMzViNzMxNzZjM2ZkOTZiZWY0Yjk2OTgwNzllNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsLnfYoiQZ07axIL1nh2dB8bcyZDK4LQ-q49GQYP1ZY">



> Hi @pedroSG94 ,
> 
> I tried to copy the source code for MixAudioSource.kt and VolumeEffect.kt as suggested, but am not able to use some methods/members (Screenshot Attached)
> 
> Am I missing something?
> 
> Thanks.
> 
> <img alt="Screenshot 2024-09-16 at 8 00 17 PM" width="784" src="https://private-user-images.githubusercontent.com/29568414/367801406-e1a24407-88c8-470d-8e89-f96218f9a805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDIxMTcsIm5iZiI6MTcyNjUwMTgxNywicGF0aCI6Ii8yOTU2ODQxNC8zNjc4MDE0MDYtZTFhMjQ0MDctODhjOC00NzBkLThlODktZjk2MjE4ZjlhODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1NTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGVlMTFjMmUxYmVlODVkNzQ3NjgyN2VmZTM4ODcwYTFkMzViNzMxNzZjM2ZkOTZiZWY0Yjk2OTgwNzllNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsLnfYoiQZ07axIL1nh2dB8bcyZDK4LQ-q49GQYP1ZY">



> Hi @pedroSG94 ,
> 
> I tried to copy the source code for MixAudioSource.kt and VolumeEffect.kt as suggested, but am not able to use some methods/members (Screenshot Attached)
> 
> Am I missing something?
> 
> Thanks.
> 
> <img alt="Screenshot 2024-09-16 at 8 00 17 PM" width="784" src="https://private-user-images.githubusercontent.com/29568414/367801406-e1a24407-88c8-470d-8e89-f96218f9a805.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1MDIxMTcsIm5iZiI6MTcyNjUwMTgxNywicGF0aCI6Ii8yOTU2ODQxNC8zNjc4MDE0MDYtZTFhMjQ0MDctODhjOC00NzBkLThlODktZjk2MjE4ZjlhODA1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE2VDE1NTAxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMGVlMTFjMmUxYmVlODVkNzQ3NjgyN2VmZTM4ODcwYTFkMzViNzMxNzZjM2ZkOTZiZWY0Yjk2OTgwNzllNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gsLnfYoiQZ07axIL1nh2dB8bcyZDK4LQ-q49GQYP1ZY">

Aaah, true. That methods was added in the same PR that this new source so it is not available. For now, test it using the default app example.
I have plan to fix it and upload a new version with all the code as soon as all bugs are solved

**Comment by sanketsirohiya** [comment] 2024-09-16 17:26
Sure, I'll wait for the positive news then. Hoping you can release one with kotlin 1.8.22 as well. :)

**Comment by pedroSG94** [comment] 2024-09-16 20:42
> Hi @pedroSG94
> 
> Do you think we should use an external microphone to avoid conflicts with the in-game or in-app microphone during recording?
> 
> P/s: Recorder app the same pubg game. No audio is recorded to live stream or video file.
> 
> https://stackoverflow.com/questions/74135716/is-there-any-way-to-determine-which-mic-of-android-phone-is-being-used-for-recor#:~:text=Most%20android%20smartphone%20has%20two,and%20One%20at%20the%20bottom.

Hello,

I was looking about this case. According with my tests if other app try to capture audio from the microphone the microphone receive silence but the device audio works. After close the app that block the microphone the audio is automatically restored and work as expected.
Depend of audio source set to the microphone instance you can modify a bit the way this works. You have the info about it here:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/sources/audio/MixAudioSource.kt#L52

No matter what you can't capture the audio in two apps at the same time but maybe using an external microphone you can solve it. I'm not sure if you can capture audio in both apps using the external microphone or you need use both microphones at the same time to work.
I haven't an external microphone to test it for now.

For example, the record screen from the system with Pixel device (that allow record both, device and microphone audio at the same time) seems to use MediaRecorder.AudioSource.VOICE_COMMUNICATION because if you try record audio from other app you always receive silence.

**Comment by noho501** [comment] 2024-09-21 09:44
Hi @pedroSG94 ,

Thank you so much for your help. With the `MediaRecorder.AudioSource.DEFAULT` and `MediaRecorder.AudioSource.MIC` options, the microphone can be restored once another app releases it. I tested it with another app, and it seems there’s no way to capture audio in two apps simultaneously, as can be done on iOS. Based on this, I think we are ready to proceed with updating the release version.

Best regards,

**Comment by pedroSG94** [comment] 2024-09-21 10:19
Hello,

I have plans to release the version this week.

This version changes the package of few classes so you will need to remove the import and import again.

**Comment by sanketsirohiya** [comment] 2024-09-30 11:39
Hey @pedroSG94, just wanted to follow up on the release activity for Mix Audio Source? When can we expect it?

**Closed** 2024-09-30 12:30 UTC

**Comment by krdhiraj03** [comment] 2025-03-20 08:17
Hi @pedroSG94 

I am using implementation 'com.github.pedroSG94.RootEncoder:library:2.5.7'

I am able to stream Screen on youtube but the audio is not streaming, Below is my ScreenService class


class ScreenService : Service(), ConnectChecker {

    companion object {
        const val TAG = "DisplayService"
        private const val CHANNEL_ID = "DisplayStreamChannel"
        const val NOTIFY_ID = 123456
        var INSTANCE: ScreenService? = null
    }

    private var notificationManager: NotificationManager? = null
    private lateinit var genericStream: GenericStream
    private var mediaProjection: MediaProjection? = null
    private val mediaProjectionManager: MediaProjectionManager by lazy {
        applicationContext.getSystemService(MEDIA_PROJECTION_SERVICE) as MediaProjectionManager
    }
    private var callback: ConnectChecker? = null
    private val width = 640
    private val height = 480
    private val vBitrate = 2500 * 1024
    private var rotation = 0 //0 for landscape or 90 for portrait
    private val sampleRate = 44100
    private val isStereo = true
    private val aBitrate = 128 * 1024
    private var prepared = false
    private var recordPath = ""
    private var selectedAudioSource: Int = 1
    private var keyFrameInterval = 2
    override fun onCreate() {
        super.onCreate()
        Log.i(TAG, "RTP Display service create")
        notificationManager = getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val channel =
                NotificationChannel(CHANNEL_ID, CHANNEL_ID, NotificationManager.IMPORTANCE_HIGH)
            notificationManager?.createNotificationChannel(channel)
        }
        genericStream =
            GenericStream(baseContext, this, NoVideoSource(), MicrophoneSource()).apply {
                //This is important to keep a constant fps because media projection only produce fps if the screen change
                getGlInterface().setForceRender(true, 30)
            }
        prepared = try {
            genericStream.prepareVideo(width, height, vBitrate, rotation = rotation, iFrameInterval = keyFrameInterval) &&
                    genericStream.prepareAudio(
                        sampleRate, isStereo, aBitrate,
                        echoCanceler = true,
                        noiseSuppressor = true
                    )
        } catch (e: IllegalArgumentException) {
            false
        }
        if (prepared) INSTANCE = this
        else Log.d(TAG, "Invalid audio or video parameters, prepare failed")
    }

    private fun keepAliveTrick() {
        val notification = NotificationCompat.Builder(this, CHANNEL_ID)
            .setSmallIcon(R.drawable.ic_launcher_background)
            .setSilent(true)
            .setOngoing(false)
            .build()
        startForeground(1, notification)
    }

    override fun onBind(p0: Intent?): IBinder? {
        return null
    }

    override fun onStartCommand(intent: Intent?, flags: Int, startId: Int): Int {
        Log.i(TAG, "RTP Display service started")
        return START_STICKY
    }

    fun sendIntent(): Intent {
        return mediaProjectionManager.createScreenCaptureIntent()
    }

    fun isStreaming(): Boolean {
        return genericStream.isStreaming
    }

    fun isRecording(): Boolean {
        return genericStream.isRecording
    }

    fun stopStream() {
        if (genericStream.isStreaming) {
            genericStream.stopStream()
            notificationManager?.cancel(NOTIFY_ID)
        }
    }

    fun setCallback(connectChecker: ConnectChecker?) {
        callback = connectChecker
    }

    override fun onDestroy() {
        super.onDestroy()
        Log.i(TAG, "RTP Display service destroy")
        stopStream()
        INSTANCE = null
        //release stream and media projection properly
        genericStream.release()
        mediaProjection?.stop()
        mediaProjection = null
    }

    @RequiresApi(Build.VERSION_CODES.Q)
    fun prepareStream(resultCode: Int, data: Intent): Boolean {
        keepAliveTrick()
        stopStream()
        mediaProjection?.stop()
        val mediaProjection = mediaProjectionManager.getMediaProjection(resultCode, data)
        this.mediaProjection = mediaProjection
        val screenSource = ScreenSource(applicationContext, mediaProjection)
        return try {
            //ScreenSource need use always setCameraOrientation(0) because the MediaProjection handle orientation.
            //You also need remove autoHandleOrientation if you are using it.
            //You need to call it after prepareVideo to override the default value.
            genericStream.getGlInterface().setCameraOrientation(0)
            genericStream.changeVideoSource(screenSource)
//            mediaProjection?.let { genericStream.changeAudioSource(InternalAudioSource(it)) }
//            Log.d(TAG, "prepareStream: ${canCaptureInternalAudio()}")
            true
        } catch (ignored: IllegalArgumentException) {
            false
        }
    }


    fun startStream(endpoint: String) {
        if (!genericStream.isStreaming) genericStream.startStream(endpoint)
    }

    //
    override fun onConnectionStarted(url: String) {
        callback?.onConnectionStarted(url)
    }

    override fun onConnectionSuccess() {
        callback?.onConnectionSuccess()
    }

    override fun onNewBitrate(bitrate: Long) {
        callback?.onNewBitrate(bitrate)
    }

    override fun onConnectionFailed(reason: String) {
        callback?.onConnectionFailed(reason)
    }

    override fun onDisconnect() {
        callback?.onDisconnect()
    }

    override fun onAuthError() {
        callback?.onAuthError()
    }

    override fun onAuthSuccess() {
        callback?.onAuthSuccess()
    }
}

am I missing something?

**Comment by pedroSG94** [comment] 2025-03-20 08:48
Hello,

You  should open a new issue instead of use a closed one.

If you can see the stream on YouTube that means that you are streaming audio properly because YouTube need video and audio to work.
Did you test the screen example without modifications to check if the audio is working properly?
You can try compare it, maybe the problem is related with this:

- You don't have the microphone in background permission properly added to the declaration of the service in the manifest.

- If you have an app using the microphone while you are streaming in background the microphone is automatically muted and only send silence. This is the way Android works because the foreground app has priority using the microphone, nothing to do.

You have a note here:
https://github.com/pedroSG94/RootEncoder/blob/master/encoder/src/main/java/com/pedro/encoder/input/sources/audio/MixAudioSource.kt#L47
```kotlin
* Tested in 2 devices (Android 12 and Android 14). This could change depend of the model or not, I'm not sure:
 * MediaRecorder.AudioSource.DEFAULT, MediaRecorder.AudioSource.MIC -> If other app open the microphone you receive buffers with silence from the microphone until the other app release the microphone (maybe you need close the app).
 * MediaRecorder.AudioSource.CAMCORDER -> Block the access to microphone to others apps. Others apps can't instantiate the microphone.
 * MediaRecorder.AudioSource.VOICE_COMMUNICATION -> Block the access to microphone to others apps. Others apps can instantiate the microphone but receive buffers with silence from the microphone.
```
