### ISSUE TITLE
Dependency version 2.5.0 is missing on jitpack

### ISSUE THREAD

**Issue by isles1217** [pedroSG94/RootEncoder#1670] opened 2024-12-03 21:16 UTC
**Describe the bug**
Our app has been using 2.5.0 since September, but recently someone was trying to build our app for the first time in a while (so not from cache), and wasn't able to get this dependency. It looks like it's 404-ing on jitpack:
https://jitpack.io/com/github/pedroSG94/RootEncoder/library/2.5.0/library-2.5.0.pom

Our project is configured to search for dependencies in the following repositories:
```
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
        maven(url = "https://jitpack.io")
    }
```

**To Reproduce**
1. Open a new android project targeting 2.5.0
2. Sync dependencies
3. Observe an error that the dependency was unable to be fetched

**Expected behavior**
Version 2.5.0 would be fetched successfully. 

**Screenshots**
N/A

**Smartphone (please complete the following information):**
 N/A

**Additional context**
If I try to target a different version (ie, 2.5.1), I'm able to retrieve that dependency without issue.

**Comment by pedroSG94** [comment] 2024-12-03 21:29
Hello,

You are right. I don't know the reason but sometimes jitpack remove old releases.
I recompiled version 2.5.0, try again

**Comment by bhavinatharva** [comment] 2024-12-19 06:51
facing same for 2.5.5 @pedroSG94

**Comment by bhavinatharva** [comment] 2024-12-19 07:33
@pedroSG94 
but other library can downloadable, any specific reason idea?

**Comment by pedroSG94** [comment] 2024-12-19 07:35
I don't know.
Maybe they are not using jitpack.io or they have a payment account with priority for this cases.
For now, I can't do anything until the login is working and I can check it. You can try with old versions

**Comment by bhavinatharva** [comment] 2024-12-19 07:40
ok Thank you for reply 👍

**Comment by pedroSG94** [comment] 2024-12-19 09:19
We can confirm that the problem is in jitpack server side:
https://github.com/jitpack/jitpack.io/issues/6743

**Comment by pedroSG94** [comment] 2024-12-19 09:26
It is working for me now. Try to compile again and let me know

**Comment by bhavinatharva** [comment] 2024-12-19 09:39
Hello @pedroSG94 

Thank you , it also working for me

**Comment by pedroSG94** [comment] 2024-12-19 09:48
Closing issue because all is solved

**Closed** 2024-12-19 10:21 UTC
