### ISSUE TITLE
About frame discarded

### ISSUE THREAD

**Issue by MePride** [pedroSG94/RootEncoder#1307] opened 2023-10-14 19:20 UTC
Hello, when using this project, I often encounter the issue of "Audio / Video frame discarded." How can I avoid it, and how can I recover the live stream after encountering this problem?

**Comment by pedroSG94** [comment] 2023-10-14 21:35
Hello,

This happens when the cache is full and you can't send packets fast enough. You are producing video/audio packets faster than you can send it.
Normally related with an internet issue because your upload speed is lower than your bitrate selected or it is not stable.

This basically inform you that the packet is discarded because the cache is full avoiding a memory errors.
A possible solution is use a lower bitrate or use bitrate adapter to reduce the bitrate on fly:
https://github.com/pedroSG94/RootEncoder/wiki/Adaptative-video-bitrate#version-164

**Comment by MePride** [comment] 2023-10-16 03:20
> Hello,
> 
> This happens when the cache is full and you can't send packets fast enough. You are producing video/audio packets faster than you can send it. Normally related with an internet issue because your upload speed is lower than your bitrate selected or it is not stable.
> 
> This basically inform you that the packet is discarded because the cache is full avoiding a memory errors. A possible solution is use a lower bitrate or use bitrate adapter to reduce the bitrate on fly: https://github.com/pedroSG94/RootEncoder/wiki/Adaptative-video-bitrate#version-164

Thks a lot 🙏, but I'm using the RtmpStream class to implement streaming. I don't need preview, and I have implemented the streaming service directly in the service.

**Comment by MePride** [comment] 2023-10-16 03:58
> Hello,
> 
> This happens when the cache is full and you can't send packets fast enough. You are producing video/audio packets faster than you can send it. Normally related with an internet issue because your upload speed is lower than your bitrate selected or it is not stable.
> 
> This basically inform you that the packet is discarded because the cache is full avoiding a memory errors. A possible solution is use a lower bitrate or use bitrate adapter to reduce the bitrate on fly: https://github.com/pedroSG94/RootEncoder/wiki/Adaptative-video-bitrate#version-164

Can the audio be turned off? Currently, it seems that there is no method to only push video to the RTMP server. In our current business, we don't need audio, so disabling the audio might help save resources to some extent.

**Comment by pedroSG94** [comment] 2023-10-16 06:49
> Can the audio be turned off? Currently, it seems that there is no method to only push video to the RTMP server. In our current business, we don't need audio, so disabling the audio might help save resources to some extent.

Hello,

In RtmpCamera2 and RtmpCamera1 you only need to skip prepareAudio.
Using RtmpStream you can try using AudioManager.Source.Disabled in the constructor

**Comment by pedroSG94** [comment] 2023-10-16 06:52
> Thks a lot 🙏, but I'm using the RtmpStream class to implement streaming. I don't need preview, and I have implemented the streaming service directly in the service.

BitrateAdapter can be applied without preview as you can see the in example

**Comment by MePride** [comment] 2023-10-17 09:41
> > Thks a lot 🙏, but I'm using the RtmpStream class to implement streaming. I don't need preview, and I have implemented the streaming service directly in the service.
> 
> BitrateAdapter can be applied without preview as you can see the in example

Very nice!! everything is working fine on my end, but sometimes there's a "Skipping iteration, frame null" issue, and I'm not sure why. And restarting devices doesn't resolve the issue either.

**Comment by MePride** [comment] 2023-10-17 16:18
> > Very nice!! everything is working fine on my end, but sometimes there's a "Skipping iteration, frame null" issue, and I'm not sure why. And restarting devices doesn't resolve the issue either.
> 
> Hello,
> 
> This happens when the rtmp library doesn't receive a frame in 1 second that is the timeout for the queue poll here: https://github.com/pedroSG94/RootEncoder/blob/master/rtmp/src/main/java/com/pedro/rtmp/rtmp/RtmpSender.kt#L147
> 
> This is not a really important log if all is working fine. Basically camera/microphone frames are added to a queue waiting for be ready to send. The log means that the queue was empty for 1 second or failed to get a frame.
> 
> Since you disabled audio. Maybe this is because you do something that freeze the video until the work finish. This could happens loading a big filter for example

Thks alot.

**Comment by pedroSG94** [comment] 2023-10-18 08:19
Closing issue as resolved. 
You can reopen if you still have problems or open other issue if the problem is not related with this

**Closed by pedroSG94** 2023-10-18 08:19 UTC
